defaultContentLanguage: "en"
baseURL: "https://t1mtw0.github.io/"
enableRobotsTXT: true
enableGitInfo: true
paginate: 15
summaryLength: 0
enableEmoji: true

outputs:
  home: ["HTML", "searchindex"]

outputFormats:
  searchindex:
    mediaType: "application/json"
    baseName: "index"
    isPlainText: true
    notAlternative: true

module:
  imports:
    - path: "github.com/omegion/hugo-omegion"

params:
  author:
    name: "Timothy Tso"
    bio:
      - "I studied Physics/Computer Science at USC. I'm also interested in and study a lot of mathematics."
    links:
      - name: "GitHub"
        url: "https://github.com/t1mtw0"
        icon: "github"
      - name: "LinkedIn"
        url: "https://linkedin.com/in/t1mtw0"
        icon: "linkedin"
  description: "Timothy Tso's Personal Website"
  dateFormat: "2 January 2006"
  enableSearch: true
  enableTableOfContents: true
  homepage:
    writingCount: 6
    workCount: 4
  search:
    recentPostsCount: 3
    recentProjectsCount: 3